# Generated by Django 3.0.14 on 2022-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(blank=True, max_length=500, verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=400, verbose_name='Название рецепта'),
        ),
    ]
