# Generated by Django 3.2.12 on 2022-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=400, unique=True, verbose_name='Название рецепта'),
        ),
    ]
